config/routes.rb
MobileMusicParty::Application.routes.draw do

  resources :mobile,
            :only => [:index, :create],
            :path => '/mobile'

  match '/' => 'party#index', :via => 'get'
  match '/' => 'party#new', :via => 'post'

  match '/shufflePlaylist' => 'party#shuffle_playlist', :via => 'post'
  match '/returnTracks' => 'party#return_playlist_tracks', :via => 'post'
  match '/addTrack' => 'party#add_track_to_playlist', :via => 'post'
  match '/createPlaylist' => 'party#create_playlist', :via => 'post'
  match '/playArtist' => 'party#return_artist_tracks', :via => 'post'
  match '/verifyArtist' => 'party#verify_artist', :via => 'post'
  match '/deleteArtist' => 'party#delete_artist', :via => 'post'

end

app/models/artist.rb
class Artist < ActiveRecord::Base
has_many :songs

end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :song
  belongs_to :artist
  belongs_to :playlist

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  has_many :songs
  has_many :artists

end

app/models/song.rb
class Song < ActiveRecord::Base
 belongs_to :artist

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/mobile_controller.rb
class MobileController < ApplicationController

  def index
    @request = Request.new
  end

  def create
      artist = params[:artist]
      song = params[:song]
      new_song = Request.new
      new_song.artist = artist
      new_song.song = song
      new_song.save

      respond_to do |format|
        format.js
      end

  end

end

app/controllers/party_controller.rb
class PartyController < ApplicationController
    require 'rubygems'

  def index
     @artists = Artist.order('artist ASC').where(:visible => true)

     @playlists = Playlist.order('playlist ASC')
  end


  def new
    num_songs = params[:num_songs].to_i
    current_songs = Request.count.to_i
    @num = current_songs - num_songs
    if current_songs - num_songs > 0
      @new_songs = Request.last(current_songs - num_songs)
    else
      @new_songs = nil
    end

    respond_to do |format|
      format.js
    end
  end

  def delete_artist
    artist_id = params[:id]

    Artist.find(artist_id).update_attributes(:visible => false)

  end

  def return_artist_tracks
    artist = params[:artist]
    search = params[:search]
    artist_id = Artist.find_by_artist(artist.strip.capitalize).id

    if search.nil?
      @condition = 'add'
    else
      @condition = nil
    end

    song_count = Song.find_all_by_artist_id(artist_id).count

    if song_count < 30
      @condition = 'updating'
      update_songs_via_lastfm(artist_id, artist)
    end

    @artist = artist
    @tracks = Song.select('song').order('priority DESC').where(:artist_id => artist_id)

    respond_to do |format|
      format.js
    end
  end

  def update_songs_via_lastfm(artist_id, artist)
    artist_array = Rockstar::Artist.new(artist, :include_info => true)
    tracks = []
    artist_array.top_tracks.each{|track| tracks << track.name }

    tracks.each do |track|
      if !Song.find_by_song(track)
        Song.create(:artist_id => artist_id, :song => track)
      end
    end
  end


  def verify_artist
     @artist = params[:artist]

     artist_array = Rockstar::Artist.new(@artist, :include_info => true)
     if !artist_array.content
       @verified = false
     else
       if Artist.find_by_artist_and_visible(@artist.strip.capitalize, false)
          Artist.find_by_artist(@artist.strip.capitalize).update_attributes(:visible => true)
          @verified = true
       elsif Artist.find_by_artist_and_visible(@artist.strip.capitalize, true)
           @verified = false
       else
         Artist.create(:artist => @artist.strip.capitalize, :visible => true)
         @verified = true
       end

     end
    @count = Artist.all.count
    respond_to do |format|
      format.js
    end
  end


  def create_playlist
     playlist = params[:playlist]

     @condition = nil
     if !Playlist.find_by_playlist(playlist)
       Playlist.create(:playlist => playlist)
       @last_record = Playlist.last
     else
       @condition = 'exists'
     end

     respond_to do |format|
       format.js
     end
  end

  def add_track_to_playlist
    playlist_id = params[:playlist_id]
    artist = params[:artist]
    song = params[:song]

    artist_id = Artist.find_by_artist(params[:artist].strip).id
    song_id = Song.find_by_song(params[:song].strip).id

     List.create(:playlist_id => playlist_id, :artist_id => artist_id, :song_id => song_id).id
    @track = List.last
    respond_to do |format|
      format.js
    end
  end

  def return_playlist_tracks
     playlist_id = params[:id]

     @tracks = List.select('song_id, artist_id').where(:playlist_id => playlist_id)


   #  Play

  end

  def shuffle_playlist
    playlist_name = params[:playlist]

    id = Playlist.find_by_playlist(playlist_name).id
    @tracks = List.select('song_id, artist_id').where(:playlist_id => id)
    @tracks.shuffle!

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mobile_side_helper.rb
module MobileSideHelper
end

app/helpers/party_helper.rb
module PartyHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MobileMusicParty</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag 'jquery-1.4.2.min' %>
  <%= csrf_meta_tag %>
      <script src="http://www.google.com/jsapi" type="text/javascript"></script>
      <script type="text/javascript"> google.load("swfobject", "2.1"); </script>
      <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mobile/_dependancies.html.erb
<script type="text/javascript" src="http://www.google.com/jsapi"></script>
<script type="text/javascript"> google.load("jquery", "1.4.2"); </script>
<script src="/javascripts/jqtouch.js" type="application/x-javascript" charset="utf-8"></script>
<style type="text/css" media="screen" href="/stylesheets/jqtouch.css"> </style>
<style type="text/css" media="screen" href="/themes/jqt/theme.css">

</style>

<script type="text/javascript">
  jQuery.jQTouch({
    icon: 'jqtouch.png',
    statusBar: 'black-translucent',
    fullScreen: true,
    formSelector: false,
    fixedViewport: true
});
</script>

app/views/mobile/create.js.erb
$('#new_request')[0].reset();
$('#request_response').html('Your request has been made successfully!').delay(3000).fadeOut(500);

app/views/mobile/index.html.erb
<%= render :partial => 'dependancies' %>
<script type="text/javascript">
    $('.submit').live('click', function(){
       $.post('<%= mobile_index_path %>', {artist:$('#artist').val(), song:$('#song').val()});
    });
</script>


<div id="jqt">
<%= form_for(@request, :url => {:action => 'create'}) do |f| %>
    <div>
        <%= f.label :artist, :class => "ui-input-text" %>
        <%= f.text_field :artist, :class => 'ui-input-text ui-body-null ui-corner-all ui-shadow-inset ui-body-d', :type => 'text', :id => 'artist' %>
    </div> <br />
    <div>
        <%= f.label :song, :class => "ui-input-text" %>
        <%= f.text_field :song, :class => 'ui-input-text ui-body-null ui-corner-all ui-shadow-inset ui-body-d', :type => 'text', :id => 'song' %>
    </div>
	<div class="ui-block-b"><div aria-disabled="false" class="ui-btn ui-btn-corner-all ui-shadow ui-btn-up-a" data-theme="a"><span class="ui-btn-inner ui-btn-corner-all"><span class="ui-btn-text">Submit</span></span><button aria-disabled="false" class="ui-btn-hidden submit" type="submit" data-theme="a">Submit</button></div></div>
<% end %>
</div>
<div id="request_response"></div>

app/views/party/add_track_to_playlist.js.erb
var counter = $('.playlist_track_listing').length;
<% track = @track %>
$('.playlist_track_listings').append("<div class='playlist_track_listing'><div class='playlist_tracks' id='playlist_track_"+counter+"'><%= track.artist.artist %> - <%= track.song.song %></div><span class='delete_playlist_track' id='delete_playlist_track_"+counter+"'><img src='/images/delete_me_small.png' alt='test' /></span></div>");

app/views/party/create_playlist.js.erb
<% if @condition %>
    alert('Playlist already exists...');
<% else %>
    <% playlist = @last_record %>
    $('.playlistQueue').append('<div class="playlist_listing" id="play_listing_<%= playlist.id %>"><div class="playlist_shortcut" id="playlist_<%= playlist.id %>"><%= playlist.playlist %></div><span class="delete_playlist" id="playlist_delete_<%= playlist.id %>"><%= image_tag 'delete_me_small.png' %></span></div>');

    $('#playlist_id').append('<option value="<%= playlist.id %>"><%= playlist.playlist %></option>');
<% end %>

app/views/party/index.html.erb
<%= javascript_include_tag 'party', 'jqtube', 'youtube_player', 'playArtist', 'playlist'  %>

<style>





    #player {border: solid 15px black;}
   .left {float: left;}
   .right {float: left;}
   .track_listing, .playlist_track_listing { cursor: pointer; border-bottom: solid 1px;  font-size: 14px;}
   .tracks {display:inline-block; width: 250px; padding: 5px;}
   .track_listing:hover, .playlist_track_listing:hover {background-color: #e5e5e5;}

    .playlist_tracks {display: inline-block; width: 330px; padding: 5px; }

    .container {  width: 100%; position: absolute; margin-left: auto; margin-right: auto;}
    #player {float: left; }

   .playlist_content_container {float: left; width: 20%; overflow-y: scroll; height: 420px; border-top: solid 5px;}
   .playlist_container {float: left; width: 12%;; overflow-y: scroll; height: 420px; border-top: solid 5px; }
   .track_container {float: left; width: 21%;; overflow-y: scroll; height: 420px; border-top: solid 5px; position: relai }
   .artist_container {float: left; width: 12%; overflow-y: scroll; height: 420px; border-top: solid 5px;  }

   .artist_listing, .playlist_listing { padding: 5px; cursor: pointer; border-bottom: solid 1px; font-size: 14px; }
   .artist_listing:hover, .playlist_listing:hover  { background-color: #e5e5e5; }

   .active {background-color: #b3b3b3; }
   .active_song {background-color: #5b98e3;}

    .controls {width: 100%; float: left; background-color: #eaeaea;}
   .artist_controls_container{ display: inline; width:480px; background-color: #eaeaea; padding: 10px; margin-right: 30px; float: right;}
   .artist_controls {width: 480px; margin-left: 100px;}

   .playlist_controls_container{ display: inline; width:480px; background-color: #eaeaea; padding: 10px; margin-right: 30px; float: left;}
   .playlist_controls {width: 480px; margin-left: 100px;}


   .add_controls_container{ display: inline; width:480px; background-color: #eaeaea; padding: 10px; float: left;}
   .add_controls {width: 480px; margin-left: 220px;}

   .error {color: red;}
   .success {color: green;}

   .delete_me, .delete_playlist {float: right; padding-right: 4px; margin: -4px; }
   .delete_playlist_track { float: right; padding-right: 4px; margin: -1px; }

   .header { border-bottom: solid 3px black; text-align: center; background-color: gray; color: white; font-weight: bold; font-family: sans-serif, helvetica; font-size: 17px; padding: 2px;}

   .artist_shortcut, .playlist_shortcut {display: inline-block; width: 150px;}

   .add_playlist {float: right; padding-right: 4px; padding-top: 5px;}





</style>


<div class="container">
    <div class="content">
        <div class="playlist_container">
            <div class="header">My Playlists</div>
            <div class="playlistQueue">
              <% @playlists.each do |playlist| %>
                   <div class="playlist_listing" id="playlist_listing_<%= playlist.id %>"><div class="playlist_shortcut" id="playlist_<%= playlist.id %>"><%= playlist.playlist %></div><span class="delete_playlist" id="playlist_delete_<%= playlist.id %>"><%= image_tag 'delete_me_small.png' %></span></div>
              <% end %>
            </div>
        </div>
        <div class="playlist_content_container">
            <div class="header">My Tracks</div>
            <div class="playlist_track_listings"></div>
        </div>

        <!-- 1. The <div> tag will contain the <iframe> (and video player) -->
        <div id="player"></div>

        <div class="artist_container">
             <div class="header">Artists</div>
              <div class="artistQueue">
                <% @artists.each do |artist| %>
                    <div class="artist_listing" id="listing_<%= artist.id %>"><div class="artist_shortcut" id="artist_<%= artist.id %>"><%= artist.artist %></div><span class="delete_me" id="delete_<%= artist.id %>"><%= image_tag 'delete_me_small.png' %></span></div>
                <% end %>
              </div>
        </div>
        <div class="track_container">
             <div class="header">Tracks</div>
            <div class="track_listings"></div>
        </div>
    </div>
<div class="controls">
   <div class="playlist_controls_container">
    <div class="playlist_controls">
        <input type="text" id="playlistTrack" value="" />
        <input type="button" value="Create Playlist" onclick="createPlaylist();"/>
        <input type="button" value="Shuffle" onclick="shufflePlaylist();" />
    </div>
   </div>

    <div class="add_controls_container">
    <div class="add_controls">
        <input type="text" id="addTrack" value="" disabled="disabled" />
        <select id="playlist_id">
          <% @playlists.each do |playlist| %>
             <option value="<%= playlist.id %>"><%= playlist.playlist %></option>
          <% end %>
        </select>
        <input type="button" value="Add Track" onclick="addTrack();"/>
    </div>
   </div>

    <div class="artist_controls_container">
    <div class="artist_controls">
        <input type="text" id="playArtist" value="" />
        <input type="button" value="Add Artist" onclick="addArtistToQueue();"/>
    </div>
    </div>
</div>


        <!--<input type="button" value="Search Artist" onclick="searchArtist();"/>-->
        <!--<input type="button" value="Previous Song" onclick="previousSong();" />-->
        <!--<input type="button" value="Next Song" onclick="nextSong();" />-->
    </div>
</div>

app/views/party/new.js.erb
<% if !@new_songs.nil? %>
var html = '';
<% @new_songs.each do |song| %>
    html += "<div class='song'><%= song.artist %>, <%= song.song %></div>";
<% end %>

jQuery('#list').append(html);

<% end %>

app/views/party/return_artist_tracks.js.erb
$('.track_listings').html('');
counter = 0;
<% @tracks.each do |track| %>
    $('.track_listings').append("<div class='track_listing'><div class='tracks' id='track_"+counter+"'><%= track.song %></div><span class='add_playlist' id='add_"+counter+"'><img src='/images/plus_sign_small.png' alt='test' /></span></div>");
counter++;
<% end %>
<% if @condition != 'search' %>
    tmpArtist = '<%= @artist %>';
<% end %>
<% if @condition == 'updating' %>
    alert('Please wait while I update the database with your requested content.');
<% end %>

if (tmpArtistCount == artist_count)
{
    $('#track_'+global_count).addClass('active');
}
buildTmpArray('.tracks');

app/views/party/return_playlist_tracks.js.erb
$('.playlist_track_listings').html('');
var counter = 0;
<% @tracks.each do |track| %>
    $('.playlist_track_listings').append("<div class='playlist_track_listing'><div class='playlist_tracks' id='playlist_track_"+counter+"'><%= track.artist.artist %> - <%= track.song.song %></div><span class='delete_playlist_track' id='delete_playlist_track_"+counter+"'><img src='/images/delete_me_small.png' alt='test' /></span></div>");
counter++;
<% end %>

if (tmpArtistCount == artist_count)
{
    $('#playlist_track_'+global_count).addClass('active');
}
buildTmpArray('.playlist_tracks');

app/views/party/shuffle_playlist.js.erb
$('.playlist_track_listings').html('');
var counter = 0;
<% @tracks.each do |track| %>
    $('.playlist_track_listings').append("<div class='playlist_track_listing'><div class='playlist_tracks' id='playlist_track_"+counter+"'><%= track.artist.artist %> - <%= track.song.song %></div><span class='delete_playlist_track' id='delete_playlist_track_"+counter+"'><img src='/images/delete_me_small.png' alt='test' /></span></div>");
counter++;
<% end %>

if (tmpArtistCount == artist_count)
{
    $('#playlist_track_'+global_count).addClass('active');
}

app/views/party/verify_artist.js.erb
 // var i = artistQueue.length;
 var i = parseInt($('.artist_listing').length);
 <% if @verified  %>
  //artistQueue.push('<%#= @artist %>');

    $('#artist_'+i).html('<%= @artist %>');
    $('#listing_'+i).append('<span class="delete_me" id="delete_'+i+'"><%= image_tag 'delete_me_small.png' %></span>');

<% else %>
    $('#artist_'+i).html('<%= @artist %> <span class="error"> (ERROR) </span>').delay(1700, function(){
       $('#listing_'+i).fadeOut(800);
    });
    //artistQueue.splice(i, 1);
<% end %>